# Generated by Django 4.0.5 on 2022-06-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_remove_posts_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
    ]
