# Generated by Django 4.0.5 on 2022-06-19 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='watch.profile'),
        ),
    ]
