# Generated by Django 4.0.5 on 2022-06-19 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Police Station', 'Police'), ('Hair&Grooming', 'Hair&Grooming'), ('Hospital', 'Hospital'), ('Mall&Markets', 'Mall&Markets'), ('Fast Foods', 'Fast Foods')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='watch.profile'),
        ),
    ]
