# Generated by Django 4.0.5 on 2022-06-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_neighbourhood_health_neighbourhood_police'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neig_id',
            new_name='neighborhood',
        ),
    ]
