# Generated by Django 4.0.5 on 2022-06-19 10:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_business_category_posts_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bsn_image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='business',
            name='weburl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Police Station', 'Police Station'), ('Hair&Grooming', 'Hair&Grooming'), ('Hospital', 'Hospital'), ('Mall&Markets', 'Mall&Markets'), ('Fast Foods', 'Fast Foods')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(upload_to='media', verbose_name='image'),
        ),
    ]
