# Generated by Django 4.0.5 on 2022-06-21 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_rename_neig_id_business_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='profile',
        ),
    ]
