# Generated by Django 4.0.5 on 2022-06-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_business_bsn_image_business_phone_business_weburl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='neig_id',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, to='watch.neighbourhood'),
        ),
    ]
