# Generated by Django 4.0.5 on 2022-06-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0007_alter_business_neig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='neig_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='watch.neighbourhood'),
        ),
    ]
