# Generated by Django 4.0.5 on 2022-06-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_neighbourhood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
