# Generated by Django 4.0.5 on 2022-06-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Neighbourhood',
        ),
    ]
